# Generated by Django 5.0.6 on 2025-08-25 03:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('categoria', models.CharField(choices=[('PlayStation', 'PlayStation'), ('Xbox', 'Xbox'), ('Nintendo', 'Nintendo'), ('PC', 'PC'), ('Otros', 'Otros')], max_length=50)),
                ('costo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('existencia', models.PositiveIntegerField()),
                ('descripcion', models.TextField()),
                ('imagen', models.ImageField(upload_to='productos/')),
            ],
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autor', models.CharField(max_length=100)),
                ('texto', models.TextField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda.producto')),
            ],
        ),
    ]
