# Generated by Django 5.0.6 on 2025-08-25 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0002_alter_comentario_autor_carrito_compra_detallecompra_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemcarrito',
            name='cantidad',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.DeleteModel(
            name='ItemCompra',
        ),
    ]
